config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  root 'home#index'

  resources :books, only: [:index, :new, :create, :update, :destroy]
  resources :films, only: [:index, :new, :create, :update, :destroy]
  resources :tv_shows, only: [:index, :new, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :author, presence: true
end

app/models/film.rb
class Film < ApplicationRecord
  validates :name, presence: true
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.sort_by(&:name)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Book added'
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :recommended_by, :complete)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all.sort_by(&:name)
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      redirect_to films_path, notice: 'Film added'
    else
      render :new
    end
  end

  private

  def film_params
    params.require(:film).permit(:name, :imdb_rating, :recommended_by, :complete)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  def index
    @tv_shows = TvShow.all.sort_by(&:name)
  end

  def new
    @tv_show = TvShow.new
  end

  def create
    @tv_show = TvShow.new(tv_show_params)
    if @tv_show.save
      redirect_to tv_shows_path, notice: 'TV show added'
    else
      render :new
    end
  end

  private

  def tv_show_params
    params.require(:tv_show).permit(:name, :imdb_rating, :recommended_by, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/books/index.html.erb
<div class='banner-image-books'> <img src="https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt=""> </div>
<div class='container list-container'>


  <div class='list-subsections'>
    <div class='list-section'>
      <h4>Books to read</h4>
      <% @books.each do |book| %>
        <% if book.complete == false %>
        <p><%= book.name %> - <%= book.author %> <span> <%= link_to 'mark as read', book_path(book), class: 'secondary-bttn' %></span></p>
        <% end %>
      <% end %>
    </div>

    <div class='list-section'>
      <h4>Books read</h4>
      <% @books.each do |book| %>
        <% if book.complete == true %>
          <p><%= book.name %> - <%= book.author %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <%= link_to  'Add book', new_book_path, class: 'bttn' %>
  </div>
</div>

app/views/books/new.html.erb
<div class='container'>
  <h3>Add a new book to your list</h3>

  <%= simple_form_for(@book) do |f| %>
    <%= f.input :name %>
    <%= f.input :author %>
    <%= f.input :recommended_by %>
    <%= f.submit :Add, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/films/index.html.erb
<div class='container list-container'>

  <div class='banner-image-films'></div>

  <div class='list-subsections'>
    <div class='list-section'>
      <h4>Films to watch</h4>
      <% @films.each do |film| %>
        <% if film.complete == false %>
        <p><%= film.name %> - IMDb rating: <%= film.imdb_rating %> <span> <%= link_to 'mark as watched', film_path(film), class: 'secondary-bttn' %></span></p>
        <% end %>
      <% end %>
    </div>

    <div class='list-section'>
      <h4>Films watched</h4>
      <% @films.each do |film| %>
        <% if film.complete == true %>
          <p><%= film.name %> - IMDb rating: <%= film.imdb_rating %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <%= link_to  'Add Film', new_film_path, class: 'bttn' %>
  </div>

</div>

app/views/films/new.html.erb
<div class='container'>
  <h3>Add a new film to your list</h3>

  <%= simple_form_for(@film) do |f| %>
    <%= f.input :name %>
    <%= f.input :imdb_rating %>
    <%= f.input :recommended_by %>
    <%= f.submit :Add, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to 'TV', tv_shows_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Films', films_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to 'Books', books_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<% film_img = 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80' %>
<% tv_img = 'https://images.unsplash.com/photo-1528928441742-b4ccac1bb04c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1364&q=80' %>
<% book_img = 'https://images.unsplash.com/photo-1513185041617-8ab03f83d6c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80' %>

  <h2 class='home-title'>Read & Watch Lists</h2>

 <div class='home-container'>
    <div class='home-section'>
      <h4>TV SHOWS</h4>
      <%= link_to image_tag(tv_img), tv_shows_path, class: 'home-img' %>
    </div>

    <div class='home-section'>
      <h4>FILMS</h4>
      <%= link_to image_tag(film_img), films_path, class: 'home-img' %>
    </div>

    <div class='home-section'>
      <h4>BOOKS</h4>
      <%= link_to image_tag(book_img), books_path, class: 'home-img light-img' %>
    </div>
 </div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Watch/Read List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div>
      <br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tv_shows/index.html.erb
<div class='container list-container'>

  <div class='banner-image-tv'></div>

  <div class='list-subsections'>
    <div class='list-section'>
      <h4>TV shows to watch</h4>
      <% @tv_shows.each do |tv_show| %>
        <% if tv_show.complete == false %>
        <p><%= tv_show.name %> - IMDb rating: <%= tv_show.imdb_rating %> <span> <%= link_to 'mark as watched', tv_show_path(tv_show), class: 'secondary-bttn' %></span></p>
        <% end %>
      <% end %>
    </div>

    <div class='list-section'>
      <h4>TV shows watched</h4>
      <% @tv_shows.each do |tv_show| %>
        <% if tv_show.complete == true %>
          <p><%= tv_show.name %> - IMDb rating: <%= tv_show.imdb_rating %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <%= link_to  'Add TV Show', new_tv_show_path, class: 'bttn' %>
  </div>
</div>

app/views/tv_shows/new.html.erb
<div class='container'>
  <h3>Add a new TV show to your list</h3>

  <%= simple_form_for(@tv_show) do |f| %>
    <%= f.input :name %>
    <%= f.input :imdb_rating %>
    <%= f.input :recommended_by %>
    <%= f.submit :Add, class: 'btn btn-primary' %>
  <% end %>

</div>